
-- Migration to update products table and seed new catalog
-- Run this in your Supabase SQL Editor

-- 1. Add missing columns
ALTER TABLE products ADD COLUMN IF NOT EXISTS brand text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS model text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS gender text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS sku text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock integer DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS tags text[];

-- 2. Clear old data (optional, to avoid conflicts or mixed data)
-- TRUNCATE products CASCADE; 

-- 3. Insert new data
INSERT INTO products (id, title, slug, brand, model, gender, category, price, sku, stock, image, images, description, condition, is_drop, tags)
VALUES
(
    'j4-red-thunder',
    'Nike Air Jordan 4 Retro Red Thunder',
    'nike-air-jordan-4-retro-red-thunder',
    'Jordan',
    'Jordan 4',
    'Hombre',
    'Zapatillas',
    189990,
    'J4-RT-001',
    5,
    '/assets/hero_red_thunder.png',
    '{"/assets/hero_red_thunder.png","/assets/prod-jordan4-back.png"}',
    'El Nike Air Jordan 4 Retro Red Thunder presenta una parte superior de nobuk negro con toques de rojo carmesí en los ojales, la lengüeta y la entresuela. La malla de rejilla en los paneles laterales y la lengüeta completa el diseño clásico.',
    'new',
    false,
    '{"jordan","retro","red thunder","sneakers"}'
),
(
    'j4-military-blue',
    'Nike Air Jordan 4 Retro Military Blue',
    'nike-air-jordan-4-retro-military-blue',
    'Jordan',
    'Jordan 4',
    'Hombre',
    'Zapatillas',
    184990,
    'J4-MB-002',
    4,
    '/assets/jordan_4_military_blue.png',
    '{"/assets/jordan_4_military_blue.png","/assets/hero_red_thunder.png"}',
    'Regresa uno de los colores más icónicos. El Jordan 4 Military Blue combina cuero blanco premium con detalles en azul militar y gris neutro, manteniendo la estética OG de 1989.',
    'new',
    false,
    '{"jordan","military blue","retro"}'
),
(
    'j4-lightning',
    'Nike Air Jordan 4 Retro Lightning',
    'nike-air-jordan-4-retro-lightning',
    'Jordan',
    'Jordan 4',
    'Hombre',
    'Zapatillas',
    179990,
    'J4-LG-003',
    6,
    '/assets/jordan_4_lightning_style.png',
    '{"/assets/jordan_4_lightning_style.png","/assets/hero_red_thunder.png"}',
    'Vibrante y audaz. El Jordan 4 Lightning destaca con su parte superior de durabuck amarillo tour y detalles en gris oscuro y negro. Un must-have para coleccionistas.',
    'new',
    false,
    '{"jordan","lightning","yellow"}'
),
(
    'j4-neon',
    'Nike Air Jordan 4 Retro Neon',
    'nike-air-jordan-4-retro-neon',
    'Jordan',
    'Jordan 4',
    'Hombre',
    'Zapatillas',
    169990,
    'J4-NE-004',
    3,
    '/assets/prod-jordan4.png',
    '{"/assets/prod-jordan4.png"}',
    'Inspirado en el Air Max 95 Neon, este Jordan 4 presenta una degradación de grises en gamuza con toques de volt neón en los ojales y la lengüeta.',
    'new',
    false,
    '{"jordan","neon","air max 95"}'
),
(
    'j4-taupe-haze',
    'Nike Air Jordan 4 Retro Taupe Haze',
    'nike-air-jordan-4-retro-taupe-haze',
    'Jordan',
    'Jordan 4',
    'Hombre',
    'Zapatillas',
    199990,
    'J4-TH-005',
    7,
    '/assets/prod-jordan4-back.png',
    '{"/assets/prod-jordan4-back.png"}',
    'Con una textura única que se desgasta con el tiempo, el Taupe Haze ofrece un look sofisticado y terroso, complementado con detalles en negro y rojo infrarrojo.',
    'new',
    false,
    '{"jordan","taupe haze","earth tone"}'
),
(
    'j5-orange-blaze',
    'Nike Air Jordan 5 Retro Orange Blaze',
    'nike-air-jordan-5-retro-orange-blaze',
    'Jordan',
    'Jordan 5',
    'Hombre',
    'Zapatillas',
    179990,
    'J5-OB-006',
    5,
    '/assets/jordan_5_orange_blaze.png',
    '{"/assets/jordan_5_orange_blaze.png"}',
    'El Jordan 5 Orange Blaze, también conocido como Shattered Backboard, presenta una combinación de cuero sail, malla blanca y acentos en naranja intenso y plata metálica.',
    'new',
    false,
    '{"jordan","orange blaze","shattered backboard"}'
),
(
    'j5-blue-suede',
    'Nike Air Jordan 5 Retro Blue Suede',
    'nike-air-jordan-5-retro-blue-suede',
    'Jordan',
    'Jordan 5',
    'Hombre',
    'Zapatillas',
    174990,
    'J5-BS-007',
    4,
    '/assets/jordan_5_orange_blaze.png',
    '{"/assets/jordan_5_orange_blaze.png"}',
    'Inspirado en los vuelos de Michael Jordan, este par presenta una parte superior completa de gamuza azul real con la clásica lengüeta reflectante del Jordan 5.',
    'new',
    false,
    '{"jordan","blue suede","royal"}'
),
(
    'j6-black-infrared',
    'Nike Air Jordan 6 Retro Black Infrared',
    'nike-air-jordan-6-retro-black-infrared',
    'Jordan',
    'Jordan 6',
    'Hombre',
    'Zapatillas',
    189990,
    'J6-BI-008',
    8,
    '/assets/jordan_4_black_infrared_style.png',
    '{"/assets/jordan_4_black_infrared_style.png"}',
    'El zapato con el que MJ ganó su primer campeonato. Regresa en su forma original con el talón ''Nike Air'', nubuck negro y los inconfundibles detalles infrarrojos.',
    'new',
    false,
    '{"jordan","infrared","og"}'
),
(
    'j6-white-yellow',
    'Nike Air Jordan 6 Retro White Yellow',
    'nike-air-jordan-6-retro-white-yellow',
    'Jordan',
    'Jordan 6',
    'Hombre',
    'Zapatillas',
    179990,
    'J6-WY-009',
    3,
    '/assets/jordan_6_white_yellow.png',
    '{"/assets/jordan_6_white_yellow.png"}',
    'Una versión fresca del Jordan 6, combinando cuero blanco con acentos amarillos vibrantes, perfecta para el verano y destacar en la cancha o la calle.',
    'new',
    false,
    '{"jordan","yellow ochre","retro"}'
),
(
    'j3-fire-red',
    'Nike Air Jordan 3 Retro Fire Red',
    'nike-air-jordan-3-retro-fire-red',
    'Jordan',
    'Jordan 3',
    'Hombre',
    'Zapatillas',
    169990,
    'J3-FR-010',
    6,
    '/assets/jordan_3_fire_red.png',
    '{"/assets/jordan_3_fire_red.png"}',
    'El diseño original de 1988 regresa con cuero blanco, estampado de elefante gris y los clásicos detalles en rojo fuego.',
    'new',
    false,
    '{"jordan","fire red","elephant print"}'
),
(
    'j3-dark-grey',
    'Nike Air Jordan 3 Retro Dark Grey',
    'nike-air-jordan-3-retro-dark-grey',
    'Jordan',
    'Jordan 3',
    'Hombre',
    'Zapatillas',
    159990,
    'J3-DG-011',
    5,
    '/assets/jordan_3_dark_grey_retry.png',
    '{"/assets/jordan_3_dark_grey_retry.png"}',
    'Sofisticación y estilo. Este Jordan 3 utiliza tonos grises oscuros y materiales premium como lana y gamuza para un look invernal elevado.',
    'new',
    false,
    '{"jordan","dark grey","wool"}'
),
(
    'j13-chicago',
    'Nike Air Jordan 13 Retro Chicago',
    'nike-air-jordan-13-retro-chicago',
    'Jordan',
    'Jordan 13',
    'Hombre',
    'Zapatillas',
    179990,
    'J13-CHI-012',
    4,
    '/assets/jordan_13_chicago_retry.png',
    '{"/assets/jordan_13_chicago_retry.png"}',
    'El diseño de pantera negra. Cuero blanco acolchado, gamuza roja y el holograma icónico en el talón definen a este clásico de Chicago.',
    'new',
    false,
    '{"jordan","chicago","he got game"}'
),
(
    'j13-navy-purple',
    'Nike Air Jordan 13 Retro Navy Purple',
    'nike-air-jordan-13-retro-navy-purple',
    'Jordan',
    'Jordan 13',
    'Hombre',
    'Zapatillas',
    169990,
    'J13-NP-013',
    3,
    '/assets/jordan_13_chicago_retry.png',
    '{"/assets/jordan_13_chicago_retry.png"}',
    'Una combinación de colores audaz con detalles en azul marino y morado, manteniendo la comodidad y el rendimiento de la suela de garra de pantera.',
    'new',
    false,
    '{"jordan","navy","court purple"}'
),
(
    'j13-black-grey',
    'Nike Air Jordan 13 Retro Black Grey',
    'nike-air-jordan-13-retro-black-grey',
    'Jordan',
    'Jordan 13',
    'Hombre',
    'Zapatillas',
    164990,
    'J13-BG-014',
    5,
    '/assets/jordan_13_chicago_retry.png',
    '{"/assets/jordan_13_chicago_retry.png"}',
    'Elegancia sigilosa. Este Jordan 13 combina cuero negro y gamuza gris para un look versátil que funciona dentro y fuera de la cancha.',
    'new',
    false,
    '{"jordan","black","grey"}'
),
(
    'j11-low-citrus',
    'Nike Air Jordan 11 Low Citrus',
    'nike-air-jordan-11-low-citrus',
    'Jordan',
    'Jordan 11',
    'Mujer',
    'Zapatillas',
    169990,
    'J11-CT-015',
    6,
    '/assets/hero-home.png',
    '{"/assets/hero-home.png"}',
    'Fresco y brillante. El Jordan 11 Low Citrus presenta cuero blanco impoluto contrastado con una suela naranja cítrica vibrante.',
    'new',
    false,
    '{"jordan","citrus","low"}'
),
(
    'vapormax-triple-black',
    'Nike Air Vapormax Triple Black',
    'nike-air-vapormax-triple-black',
    'Nike',
    'Vapormax',
    'Unisex',
    'Zapatillas',
    149990,
    'VP-TB-016',
    8,
    '/assets/prod-airmax.png',
    '{"/assets/prod-airmax.png"}',
    'Amortiguación aire revolucionaria de punta a talón. El acabado Triple Black ofrece un look furtivo y moderno para la ciudad.',
    'new',
    false,
    '{"nike","vapormax","black"}'
),
(
    'dunk-low-olive',
    'Nike Dunk Low Olive',
    'nike-dunk-low-olive',
    'Nike',
    'Dunk',
    'Hombre',
    'Zapatillas',
    129990,
    'DK-OL-017',
    10,
    '/assets/dunk_low_olive.png',
    '{"/assets/dunk_low_olive.png"}',
    'El ícono del baloncesto de los 80 regresa con colores clásicos y cuero impecable. El tono Olive aporta un toque militar y urbano.',
    'new',
    false,
    '{"nike","dunk","olive"}'
),
(
    'hoodie-navy',
    'Hoodie Lukstore Graffiti Navy',
    'hoodie-lukstore-graffiti-navy',
    'Lukstore',
    'Hoodie Essential',
    'Unisex',
    'Streetwear',
    49990,
    'AP-HN-018',
    20,
    '/assets/hoodie_navy_urban.png',
    '{"/assets/hoodie_navy_urban.png"}',
    'Polerón de algodón pesado premium con estampado de graffiti minimalista. Corte boxy fit para máxima comodidad y estilo urbano.',
    'new',
    false,
    '{"apparel","hoodie","navy"}'
),
(
    'tee-tag-white',
    'Polera Lukstore Tag White',
    'polera-lukstore-tag-white',
    'Lukstore',
    'T-Shirt Boxy',
    'Unisex',
    'Streetwear',
    29990,
    'AP-TW-019',
    25,
    '/assets/tshirt_white_tag.png',
    '{"/assets/tshirt_white_tag.png"}',
    'Básico elevado. Algodón 240gsm de tacto suave. Detalle de etiqueta tejida Lukstore en el dobladillo inferior.',
    'new',
    false,
    '{"apparel","t-shirt","white"}'
),
(
    'banano-urban-black',
    'Banano Lukstore Urban Tag Black',
    'banano-lukstore-urban-tag-black',
    'Lukstore',
    'Banano Tech',
    'Unisex',
    'Accesorios',
    24990,
    'AC-BB-020',
    15,
    '/assets/hero-home.png',
    '{"/assets/hero-home.png"}',
    'Funcionalidad y estilo callejero. Múltiples compartimentos, correa ajustable y materiales resistentes al agua.',
    'new',
    false,
    '{"accessories","bag","black"}'
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    slug = EXCLUDED.slug,
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    gender = EXCLUDED.gender,
    category = EXCLUDED.category,
    price = EXCLUDED.price,
    sku = EXCLUDED.sku,
    stock = EXCLUDED.stock,
    image = EXCLUDED.image,
    images = EXCLUDED.images,
    description = EXCLUDED.description,
    condition = EXCLUDED.condition,
    is_drop = EXCLUDED.is_drop,
    tags = EXCLUDED.tags;
